kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: default
    name: snapshot-controller-runner
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: snapshot-controller-role
  rules:
    - apiGroups: [""]
      resources: ["persistentvolumes", "endpoints"]
      verbs: ["get", "list", "watch", "create", "delete"]
    - apiGroups: [""]
      resources: ["persistentvolumeclaims", "endpoints"]
      verbs: ["get", "list", "watch", "update"]
    - apiGroups: ["storage.k8s.io"]
      resources: ["storageclasses"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["list", "watch", "create", "update", "patch"]
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["create", "list", "watch", "delete"]
    - apiGroups: ["volumesnapshot.external-storage.k8s.io"]
      resources: ["volumesnapshots", "endpoints"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    - apiGroups: ["volumesnapshot.external-storage.k8s.io"]
      resources: ["volumesnapshotdatas", "endpoints"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: snapshot-controller
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: snapshot-controller-role
  subjects:
  - kind: ServiceAccount
    name: snapshot-controller-runner
    namespace: default
- apiVersion: v1
  kind: Secret
  metadata:
    name: awskeys
  type: Opaque
  data:
    access-key-id: QUtJQUpRM1BKN1ZHNVUzWDY2WVEK
    secret-access-key: ZTYxMDFjS1JWUlY1aFB0aklqb0RsUTBIU2tGRTdNc0RIYmNIZ0cwTQo=
