apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
  namespace: default
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: slow
  resources:
    requests:
      storage: 4Gi
