apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumebackupproviders.backups.example.com
spec:
  group: backups.example.com
  names:
    kind: VolumeBackupProvider
    listKind: VolumeBackupProviderList
    plural: volumebackupproviders
    singular: volumebackupprovider
    shortNames:
    - vbps
    - vbp
  scope: Cluster
  version: v1alpha1
  subresources:
    status: {}
