apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumebackups.backups.example.com
spec:
  group: backups.example.com
  names:
    kind: VolumeBackup
    listKind: VolumeBackupList
    plural: volumebackups
    singular: volumebackup
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
