apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: hostpath-pvc
  hostPath:
    path: /tmp/test
